//! Offline Ed25519 licensing for Folio Pro.
//!
//! License format: `FOLIO1-<base64url-no-pad(payload)>-<base64url-no-pad(signature)>`
//! where the payload is the canonical compact JSON
//! `{"email":"...","issued":"YYYY-MM-DD"}` (field order fixed, no whitespace —
//! the exact `serde_json` serialization of [`LicensePayload`]) and the
//! signature is Ed25519 over the raw payload bytes, i.e. the exact bytes that
//! get base64url-encoded into the middle segment. No expiry, no network.

use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

/// ————————————————————————— DEV-ONLY KEYPAIR —————————————————————————
/// This keypair exists so development and tests can mint and verify
/// licenses. The PRIVATE key below is public knowledge by definition —
/// do NOT ship real customer licenses signed with it. The production
/// signing key must be generated by the vendor (`folio-license keygen`),
/// kept offline, and never committed; only its public half replaces
/// `PUBLIC_KEY_HEX` below.
pub const DEV_PRIVATE_KEY_HEX: &str =
    "aee40709778252f323b51ee39b5205103a61a07be2554744d64ca2beac97bfab";
pub const DEV_PUBLIC_KEY_HEX: &str =
    "6b3eb6ed53d51e10d27ac5d95207394d805d97191e637e578bc527a6437cdc7f";

/// The public key the app verifies licenses against. Points at the dev
/// keypair until a production signing key exists.
pub const PUBLIC_KEY_HEX: &str = DEV_PUBLIC_KEY_HEX;

pub const LICENSE_PREFIX: &str = "FOLIO1";
pub const LICENSE_FILE_NAME: &str = "license.json";

/// Canonical license payload. Field declaration order defines the
/// canonical byte serialization signed by the vendor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LicensePayload {
    pub email: String,
    pub issued: String,
}

/// Result of verifying a license string (section: app-side info).
#[derive(Debug, Clone, Serialize)]
pub struct LicenseInfo {
    pub valid: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// What the frontend needs to gate features.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct LicenseState {
    pub licensed: bool,
    pub email: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LicenseError {
    WrongPrefix,
    WrongSegmentCount,
    InvalidPayloadEncoding,
    InvalidSignatureEncoding,
    SignatureMismatch,
    InvalidPayloadJson,
}

impl std::fmt::Display for LicenseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let msg = match self {
            LicenseError::WrongPrefix => "not a Folio license (expected the FOLIO1- prefix)",
            LicenseError::WrongSegmentCount => "malformed license (expected three segments)",
            LicenseError::InvalidPayloadEncoding => "malformed license (payload is not base64url)",
            LicenseError::InvalidSignatureEncoding => {
                "malformed license (signature is not base64url)"
            }
            LicenseError::SignatureMismatch => "invalid license (signature does not match)",
            LicenseError::InvalidPayloadJson => "invalid license (payload is not valid JSON)",
        };
        f.write_str(msg)
    }
}

// ——— hex helpers (kept dependency-free) ———

pub fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn from_hex(s: &str) -> Result<Vec<u8>, String> {
    if s.len() % 2 != 0 {
        return Err("hex string has odd length".to_string());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).map_err(|e| e.to_string()))
        .collect()
}

pub fn signing_key_from_hex(hex: &str) -> Result<SigningKey, String> {
    let bytes = from_hex(hex)?;
    let bytes: [u8; 32] = bytes
        .try_into()
        .map_err(|_| "private key must be 32 bytes (64 hex chars)".to_string())?;
    Ok(SigningKey::from_bytes(&bytes))
}

pub fn verifying_key_from_hex(hex: &str) -> Result<VerifyingKey, String> {
    let bytes = from_hex(hex)?;
    let bytes: [u8; 32] = bytes
        .try_into()
        .map_err(|_| "public key must be 32 bytes (64 hex chars)".to_string())?;
    VerifyingKey::from_bytes(&bytes).map_err(|e| e.to_string())
}

/// Generate a fresh keypair, returned as `(private_hex, public_hex)`.
pub fn generate_keypair() -> (String, String) {
    let mut rng = rand_core::OsRng;
    let signing = SigningKey::generate(&mut rng);
    let verifying = signing.verifying_key();
    (to_hex(&signing.to_bytes()), to_hex(&verifying.to_bytes()))
}

/// The DEV signing key — panics if the constant above is not valid hex,
/// which the unit tests guard against.
pub fn dev_signing_key() -> SigningKey {
    signing_key_from_hex(DEV_PRIVATE_KEY_HEX).expect("DEV_PRIVATE_KEY_HEX must be valid")
}

/// Canonical payload bytes: compact serde_json of {email, issued}, field
/// order fixed by the struct. These exact bytes are signed and are the
/// exact bytes base64url-encoded into the license's middle segment.
fn payload_bytes(payload: &LicensePayload) -> Vec<u8> {
    serde_json::to_vec(payload).expect("LicensePayload serialization is infallible")
}

/// Mint a license string for `email` with issue date `issued` (YYYY-MM-DD).
pub fn create_license(email: &str, issued: &str, signing_key: &SigningKey) -> String {
    let payload = LicensePayload {
        email: email.to_string(),
        issued: issued.to_string(),
    };
    let bytes = payload_bytes(&payload);
    let signature = signing_key.sign(&bytes);
    format!(
        "{LICENSE_PREFIX}-{}-{}",
        URL_SAFE_NO_PAD.encode(&bytes),
        URL_SAFE_NO_PAD.encode(signature.to_bytes())
    )
}

/// base64url-no-pad length of a 64-byte Ed25519 signature: 64 bytes =
/// 21 full triples (84 chars) + 1 leftover byte (2 chars) = 86 chars.
/// The length is fixed, which is what makes `-` usable as the segment
/// delimiter even though `-` is itself a base64url character.
const SIG_B64_LEN: usize = 86;

/// Parse and verify a license string against the embedded public key.
pub fn verify_license(key: &str) -> Result<LicensePayload, LicenseError> {
    let key = key.trim();
    let Some(rest) = key
        .strip_prefix(LICENSE_PREFIX)
        .and_then(|r| r.strip_prefix('-'))
    else {
        return Err(LicenseError::WrongPrefix);
    };
    // Anchor on the fixed-length signature at the end: `payload-signature`.
    if rest.len() <= SIG_B64_LEN {
        return Err(LicenseError::WrongSegmentCount);
    }
    let (head, sig_seg) = rest.split_at(rest.len() - SIG_B64_LEN);
    let Some(payload_seg) = head.strip_suffix('-') else {
        return Err(LicenseError::WrongSegmentCount);
    };
    if payload_seg.is_empty() {
        return Err(LicenseError::WrongSegmentCount);
    }

    let payload_bytes = URL_SAFE_NO_PAD
        .decode(payload_seg)
        .map_err(|_| LicenseError::InvalidPayloadEncoding)?;
    let sig_bytes = URL_SAFE_NO_PAD
        .decode(sig_seg)
        .map_err(|_| LicenseError::InvalidSignatureEncoding)?;
    // 86 no-pad base64url chars always decode to exactly 64 bytes.
    let sig_bytes: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| LicenseError::InvalidSignatureEncoding)?;

    let verifying = verifying_key_from_hex(PUBLIC_KEY_HEX)
        .map_err(|_| LicenseError::SignatureMismatch)?;
    let signature = Signature::from_bytes(&sig_bytes);
    verifying
        .verify(&payload_bytes, &signature)
        .map_err(|_| LicenseError::SignatureMismatch)?;

    // The signature already commits to these exact bytes; parse them.
    serde_json::from_slice(&payload_bytes).map_err(|_| LicenseError::InvalidPayloadJson)
}

/// Verify and shape the result for the frontend.
pub fn verify_license_info(key: &str) -> LicenseInfo {
    match verify_license(key) {
        Ok(payload) => LicenseInfo {
            valid: true,
            email: Some(payload.email),
            error: None,
        },
        Err(e) => LicenseInfo {
            valid: false,
            email: None,
            error: Some(e.to_string()),
        },
    }
}

// ——— persistence (license.json in the app config dir) ———

#[derive(Debug, Serialize, Deserialize)]
struct StoredLicense {
    email: String,
    key: String,
}

/// Persist a verified license to `<dir>/license.json`.
pub fn store_license(dir: &Path, email: &str, key: &str) -> Result<(), String> {
    fs::create_dir_all(dir).map_err(|e| format!("failed to create config dir: {e}"))?;
    let stored = StoredLicense {
        email: email.to_string(),
        key: key.to_string(),
    };
    let json = serde_json::to_string_pretty(&stored).map_err(|e| e.to_string())?;
    fs::write(dir.join(LICENSE_FILE_NAME), json)
        .map_err(|e| format!("failed to write license file: {e}"))
}

/// Read the persisted license and re-verify its signature — the file is
/// never trusted blindly. Any problem (missing, corrupt, tampered)
/// yields the unlicensed state rather than an error.
pub fn load_license_state(dir: &Path) -> LicenseState {
    let unlicensed = || LicenseState {
        licensed: false,
        email: None,
    };

    let Ok(json) = fs::read_to_string(dir.join(LICENSE_FILE_NAME)) else {
        return unlicensed();
    };
    let Ok(stored) = serde_json::from_str::<StoredLicense>(&json) else {
        return unlicensed();
    };
    match verify_license(&stored.key) {
        // The stored email must agree with the signed payload.
        Ok(payload) if payload.email == stored.email => LicenseState {
            licensed: true,
            email: Some(payload.email),
        },
        _ => unlicensed(),
    }
}

/// Remove the persisted license, if any.
pub fn clear_stored_license(dir: &Path) -> Result<(), String> {
    match fs::remove_file(dir.join(LICENSE_FILE_NAME)) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("failed to remove license file: {e}")),
    }
}

/// Today's date in UTC as YYYY-MM-DD (used by the CLI for `issued`).
pub fn today_utc() -> String {
    let days = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| (d.as_secs() / 86_400) as i64)
        .unwrap_or(0);
    civil_from_days(days)
}

/// Days-since-epoch → civil date (Howard Hinnant's algorithm).
fn civil_from_days(days: i64) -> String {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{y:04}-{m:02}-{d:02}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dev_license(email: &str) -> String {
        create_license(email, "2026-07-24", &dev_signing_key())
    }

    fn temp_dir(name: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!("folio-license-test-{name}-{}", std::process::id()))
    }

    #[test]
    fn dev_keypair_constants_are_consistent() {
        let signing = dev_signing_key();
        assert_eq!(
            to_hex(signing.verifying_key().as_bytes()),
            DEV_PUBLIC_KEY_HEX,
            "dev private/public key constants must match"
        );
        assert!(!DEV_PRIVATE_KEY_HEX.bytes().all(|b| b == b'0'));
    }

    #[test]
    fn canonical_payload_serialization() {
        let payload = LicensePayload {
            email: "a@b.c".to_string(),
            issued: "2026-07-24".to_string(),
        };
        assert_eq!(
            payload_bytes(&payload),
            br#"{"email":"a@b.c","issued":"2026-07-24"}"#.to_vec()
        );
    }

    #[test]
    fn valid_round_trip() {
        let key = dev_license("writer@example.com");
        let payload = verify_license(&key).unwrap();
        assert_eq!(payload.email, "writer@example.com");
        assert_eq!(payload.issued, "2026-07-24");
    }

    #[test]
    fn tampered_payload_rejected() {
        let key = dev_license("writer@example.com");
        // Flip one character inside the payload segment (stays base64url).
        let mut chars: Vec<char> = key.chars().collect();
        let i = LICENSE_PREFIX.len() + 3;
        chars[i] = if chars[i] == 'A' { 'B' } else { 'A' };
        let tampered: String = chars.into_iter().collect();
        let err = verify_license(&tampered).unwrap_err();
        assert!(
            matches!(
                err,
                LicenseError::SignatureMismatch | LicenseError::InvalidPayloadEncoding
            ),
            "unexpected error: {err:?}"
        );
    }

    #[test]
    fn wrong_key_rejected() {
        let (other_private, _) = generate_keypair();
        let key = create_license("writer@example.com", "2026-07-24", &signing_key_from_hex(&other_private).unwrap());
        assert_eq!(
            verify_license(&key).unwrap_err(),
            LicenseError::SignatureMismatch
        );
    }

    #[test]
    fn malformed_strings_rejected() {
        let sig86 = "A".repeat(SIG_B64_LEN);

        assert_eq!(
            verify_license("").unwrap_err(),
            LicenseError::WrongPrefix
        );
        assert_eq!(
            verify_license("FOLIO2-AAAA-BBBB").unwrap_err(),
            LicenseError::WrongPrefix
        );
        // Too short to hold a fixed-length signature segment.
        assert_eq!(
            verify_license("FOLIO1-onlyone").unwrap_err(),
            LicenseError::WrongSegmentCount
        );
        assert_eq!(
            verify_license("FOLIO1-a-b-c").unwrap_err(),
            LicenseError::WrongSegmentCount
        );
        // Right length, but no '-' delimiter before the signature segment.
        assert_eq!(
            verify_license(&format!("FOLIO1-AAAA{sig86}")).unwrap_err(),
            LicenseError::WrongSegmentCount
        );
        // Payload is not base64url.
        assert_eq!(
            verify_license(&format!("FOLIO1-AAAA!AAAA-{sig86}")).unwrap_err(),
            LicenseError::InvalidPayloadEncoding
        );
        // Signature is not base64url ('!' is outside the alphabet).
        assert_eq!(
            verify_license(&format!("FOLIO1-AAAA-{}!", "A".repeat(SIG_B64_LEN - 1)))
                .unwrap_err(),
            LicenseError::InvalidSignatureEncoding
        );
        // Well-formed but never signed by the embedded key.
        assert_eq!(
            verify_license(&format!("FOLIO1-AAAA-{sig86}")).unwrap_err(),
            LicenseError::SignatureMismatch
        );
    }

    #[test]
    fn signed_non_json_payload_rejected() {
        // Signature is valid but the payload bytes are not JSON.
        let signing = dev_signing_key();
        let bytes = b"not json".to_vec();
        let sig = signing.sign(&bytes);
        let key = format!(
            "{LICENSE_PREFIX}-{}-{}",
            URL_SAFE_NO_PAD.encode(&bytes),
            URL_SAFE_NO_PAD.encode(sig.to_bytes())
        );
        assert_eq!(
            verify_license(&key).unwrap_err(),
            LicenseError::InvalidPayloadJson
        );
    }

    #[test]
    fn persistence_write_read_reverify() {
        let dir = temp_dir("roundtrip");
        let key = dev_license("writer@example.com");

        store_license(&dir, "writer@example.com", &key).unwrap();
        let state = load_license_state(&dir);
        assert!(state.licensed);
        assert_eq!(state.email.as_deref(), Some("writer@example.com"));

        clear_stored_license(&dir).unwrap();
        assert!(!load_license_state(&dir).licensed);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn corrupted_file_is_unlicensed_not_an_error() {
        let dir = temp_dir("corrupt");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(LICENSE_FILE_NAME), "{not json").unwrap();
        assert!(!load_license_state(&dir).licensed);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn tampered_stored_key_is_unlicensed() {
        let dir = temp_dir("tampered");
        let (other_private, _) = generate_keypair();
        let key = create_license(
            "writer@example.com",
            "2026-07-24",
            &signing_key_from_hex(&other_private).unwrap(),
        );
        store_license(&dir, "writer@example.com", &key).unwrap();
        assert!(!load_license_state(&dir).licensed);

        // Stored email disagreeing with the signed payload is also rejected.
        let good = dev_license("writer@example.com");
        store_license(&dir, "attacker@example.com", &good).unwrap();
        assert!(!load_license_state(&dir).licensed);

        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn today_utc_is_yyyy_mm_dd() {
        let today = today_utc();
        assert_eq!(today.len(), 10);
        assert_eq!(&today[4..5], "-");
        assert_eq!(&today[7..8], "-");
        assert!(today.bytes().all(|b| b.is_ascii_digit() || b == b'-'));
    }
}
